[package]
name = "generate_data"
version = "0.1.0"
edition = "2021"

[dependencies]
fake = { version = "3.0", features = ["chrono"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rand = "0.8"

