/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type HyperionDBWrapper = HyperionDbWrapper
export declare class HyperionDbWrapper {
  constructor()
  initialize(numShards: number, dataDir: string, indexedFields: Array<[string, string]>, address: string): Promise<void>
  startServer(port: number): Promise<void>
  query(queryStr: string): Promise<string>
}
